### PR TITLE
Move ndvi intro and general cleanup

### PR DESCRIPTION
**Pull request by ErinBecker**
This PR does the following from https://github.com/datacarpentry/r-raster-vector-geospatial/issues/165:
- [x] move intro to time series data and image to organization lesson
- [x] Move NDVI and RGB sections to organization lesson

Both of these sections come from the raster/vector lesson, [episode 12](https://datacarpentry.org/r-raster-vector-geospatial/12-time-series-raster/index.html). This PR does not put them into the correct position in this lesson. I want to finish moving over all of the intro sections and then organize this lesson. Please review and merge if this strategy seems ok to you. @tyson-swetnam @chris-prener

### CODE REVIEW

**Comment by ErinBecker** [comment]
Hey @tyson-swetnam @chris-prener - I'm about to start going through this lesson and re-order the material in a way that makes sense. I moved over a bunch of intro materials from the raster vector lesson, but didn't put them in any particular order. I've finished going through all of the raster vector episodes now and am ready to clean up this lesson. Could I get a review and/or merge on this one so all the content is in place for the cleanup? @datacarpentry/geospatial-maintainers

**Comment by chris-prener** [comment]
happy to @ErinBecker !

**Comment by ErinBecker** [comment]
Edit: I've started to add general clean-up changes to this PR. This includes fixing links, fixing images, moving "additional info" to callout boxes, and trying to put things in the right order. This is a work in progress, but please feel free to review and/or merge at any stage.

**Comment by chris-prener** [comment]
I just gave it a quick pass - I think we'll want to build out the description of what a shapefiles is just a bit more. I'm not sure what others think (calling on @jsta @lwasser) but I felt like the stuff on `proj` and `wkt` might be too in the weeds for folks not familiar with geospatial work at all?

**Comment by ErinBecker** [comment]
Thanks @chris-prener! Do you think we should merge this as is and add new PRs on top of these changes? Or do it all in one big push?

**Comment by chris-prener** [comment]
I think merging this is fine and then we can add new PRs (perhaps after some discussion about level of detail) @ErinBecker !

**Pull request merged**
