### PR TITLE
Move intro to multiband rasters from raster vector lesson

### PR DESCRIPTION
**Pull request by ErinBecker**
This PR moves the information from the top of [episode 5](http://www.datacarpentry.org/r-raster-vector-geospatial/05-raster-multi-band-in-r/index.html) to this introductory lesson. I think I still need to move some images over, but the text is here now.

### CODE REVIEW

**Comment by obrl-soil** [comment]
This is probably the right place for the topic, but this doesn't flow very well. The content should be further up I think, before vector is discussed.

**Comment by ErinBecker** [comment]
Thanks @obrl-soil for taking a look, I'll move it to before the vector section.

**Comment by ErinBecker** [comment]
That should do it. Please let me know what you think and merge if it looks ready.

**Comment by obrl-soil** [comment]
Yeah that looks awesome

**Review by obrl-soil — COMMENTED** [review]
core content is now in one place and flows well

**Comment by ErinBecker** [comment]
Thanks @obrl-soil! I'm still reading through the raster vector lessons and might find other things to move over to this introductory lesson over the next few days. Once I've gone through all of that material, I'd like to go through this lesson again and try to find places to add exercises and/or discussions. I'm worried that the material will be too lecturery and we don't want that to be their first experience at the workshop. Too easy to lose people if the first hour or so is a lecture. Let me know if you have any ideas of where we can insert exercises and/or discussions!

**Pull request merged**
