### PR TITLE
raster and rgdal eliminated.

### LINKED ISSUE #88: replace rgdal and rgeos with equivalent calls from sf or terra
### What is the problem?

The introduction episode along with several files in the `code/` folder (which is unused in the lesson) still have `library(rgdal)`, which is now causing the lesson to fail building due to the fact that the {rgdal} package is now retired.

This was opened in the r-raster-vector-geospatial lesson in 2021: https://github.com/datacarpentry/r-raster-vector-geospatial/issues/363 and the @datacarpentry/curriculum-advisors-geospatial had [made a recommendation to replace rgdal and rgeos with calls from sf or terra](https://github.com/datacarpentry/curriculum-advisors/blob/main/geospatial/2022Q1_Geospatial_CAC_Minutes.md):

> * Deprecation of the sp, rgeos, and rgdal packages
>   
>   * The Committee agreed that the references to rgdal and rgeos be removed or replaced with references to the equivalent sf and terra functions as appropriate. This decision is closely paired with the rationale for choosing terra as the replacement for the raster package and aims to avoid code-breaking deprecations coming some time in 2023.
> * Transition from raster to terra or stars
>   
>   * The terra package appears to be the most direct replacement for raster as it uses language which is similar to raster and common to other GIS. The Committee recommends that terra be adopted as a replacement to raster. Stars should be presented as an alternative to terra that may be faster in some cases or more appropriate for analyses with longitudinal elements.

### Location of problem (optional)

https://github.com/search?q=repo%3Adatacarpentry%2Forganization-geospatial+%28rgdal+OR+rgeos%29&type=code

### PR DESCRIPTION
**Pull request by jonjab**
Closes #88 

I updated scripts and calls to libraries in each episode to eliminate raster and rgdal.

This lesson also has a code directory, inside of which is a lot of dead and defunct code that reads as leftover from the development of the lesson. I edited it enough so that the repo builds in workbench, but it might be a good idea to get rid of that entire /code/ directory.

### CODE REVIEW

**Review by tobyhodges — APPROVED** [review]
Looks great to me. Thanks so much @jonjab, I really appreciate you taking the time to work on this.

I will leave it open for a few more days, in case any of the lesson Maintainers also want to take a look. I will come back and merge next week if not.

**Comment by tobyhodges** [comment]
Ah, looks like maybe the `code/R/dc-spatio-temporal-intro/07-spatial-resolution-extent.R` file still needs to have `raster` and `rgdal` removed?

I think we will have to update the `renv.lock` file too, to remove the packages as dependencies, before this will build. I can take care of that, if needed.

**Comment by jonjab** [comment]
I don't know anything about how to do the renv.lock file, 
but I did take care of ep7.r in my fork.

**Comment by tobyhodges** [comment]
Merging this now, so that I can take care of the lockfile more easily

**Pull request merged**
